export const APP_LOAD_BEGIN = "APP_LOAD_BEGIN";
export const APP_LOAD_SUCCESS = "APP_LOAD_SUCCESS";
export const APP_LOAD_FAILURE = "APP_LOAD_FAILURE";
export const APP_LOAD_DISMISS_ERROR = "APP_LOAD_DISMISS_ERROR";

export const APP_OPEN_CLOSE_MENU = "APP_OPEN_CLOSE_MENU";
